# Generated by Django 2.2.12 on 2020-05-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20200513_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='FotoUser',
            field=models.ImageField(default='user.png', upload_to=None, verbose_name='Foto de perfil'),
        ),
    ]
