# Generated by Django 2.2.12 on 2020-05-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20200513_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='FotoUser',
            field=models.ImageField(default='user.png', upload_to='perfiles/img', verbose_name='Foto de perfil'),
        ),
    ]
