# Generated by Django 2.2.12 on 2020-05-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_auto_20200520_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='FotoUser',
            field=models.ImageField(default='user.png', upload_to='perfil', verbose_name='Foto de perfil'),
        ),
    ]
