# Generated by Django 2.2.12 on 2020-06-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_auto_20200619_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='FotoUser',
            field=models.ImageField(default='user.png', upload_to='img/perfil', verbose_name='Foto de perfil'),
        ),
    ]
