# Generated by Django 2.2.12 on 2020-05-13 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0004_auto_20200513_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lenguaje', models.CharField(max_length=45, verbose_name='Lenguaje de programacion')),
                ('MorotDB', models.CharField(max_length=155, verbose_name='Motor de base de datos')),
                ('Arquitectura', models.CharField(max_length=255, verbose_name='Aquitectura de software')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='tipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTiDoc', models.CharField(max_length=45, verbose_name='Nombre tipo documento')),
            ],
            options={
                'verbose_name': 'Tipo documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombProy', models.CharField(max_length=255, verbose_name='Nombre del proyecto')),
                ('DescProy', models.TextField(max_length=2000, verbose_name='Descripcion del proyecto')),
                ('ImgPorye', models.ImageField(default='proy.png', upload_to='', verbose_name='Foto del proyecto')),
                ('FechaIni', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Iniciado el')),
                ('FechaFin', models.DateTimeField(auto_now=True, null=True, verbose_name='Terminado el')),
                ('UrlRepo', models.TextField(max_length=2000, verbose_name='Link del repositorio')),
                ('EstaProy', models.CharField(max_length=45, verbose_name='Estado del proyecto')),
                ('idCategProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CateProye', verbose_name='Identificador de categoria de proyectos')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombDocu', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('PathDocu', models.FileField(max_length=45, upload_to=None, verbose_name='Ruta del documento')),
                ('idProyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Identificador de proyecto')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.tipoDocu', verbose_name='Identificador del tipo de documento')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Identificador de usuario')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
